service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  profile: personal
  stage: production

functions:
  api:
    handler: index.handler
    environment:
      POSTGRES_USERNAME: ''
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST: ''
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ''
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: 123
    apiKey: ''