service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  profile: personal
  stage: production

functions:
  api:
    handler: index.handler
    environment:
      NEW_RELIC_LAMBDA_HANDLER: index.handler
      NEW_RELIC_LICENSE_KEY: ''
      NEW_RELIC_NO_CONFIG_FILE: true
      NEW_RELIC_APP_NAME: ""
      NEW_RELIC_ACCOUNT_ID: 123
      NEW_RELIC_TRUSTED_ACCOUNT_KEY: 123
      NEW_RELIC_LOG_ENABLED: true
      NEW_RELIC_LOG: 'stdout'
      POSTGRES_USERNAME: ''
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST: ''
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ''
    layers:
      - arn:aws:lambda:us-west-2:451483290750:layer:NewRelicNodeJS18X:16
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  # - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: 3836132
    apiKey: 'xxx'
    disableLicenseKeySecret: true
